services:
  db:
    image: postgres:17
    container_name: db
    env_file:
      - db.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - assistant_bridge

  migrator:
    build:
      context: .
      dockerfile: migrator/Dockerfile
    container_name: migrator
    restart: no
    env_file:
      - .env
    volumes:
      - ./migrator/migrations/:/app/migrations/
    depends_on:
      - db
    networks:
      - assistant_bridge

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ~/upload/:/app/upload/
    networks:
      - assistant_bridge
    depends_on:
      - db
      - migrator

  worker-manager:
    build:
      context: .
      dockerfile: worker-manager/Dockerfile
    container_name: worker-manager
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./worker-manager/infrastructure/docker/worker-settings:/app/infrastructure/docker/worker-settings
    networks:
      - assistant_bridge
    depends_on:
      - db
      - migrator

  watcher:
    build:
      context: .
      dockerfile: watcher/Dockerfile
    container_name: watcher
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - assistant_bridge
    depends_on:
      - db
      - migrator

  admin-backend:
    build:
      context: .
      dockerfile: admin/backend/Dockerfile
    container_name: admin-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ~/upload/:/app/upload/
    networks:
      - assistant_bridge
    depends_on:
      - db
      - migrator

  admin-frontend:
    build:
      context: admin/frontend
      dockerfile: Dockerfile
    container_name: admin-frontend
    restart: unless-stopped
    depends_on:
      - admin-backend
    volumes:
      - ./admin/frontend/nginx.conf:/etc/nginx/nginx.conf:ro

  posts:
    build:
      context: .
      dockerfile: posts-service/Dockerfile
    container_name: posts-service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./posts-service/jobs.sqlite:/app/jobs.sqlite
    networks:
      - assistant_bridge
    depends_on:
      - db
      - migrator
      - worker-manager

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    volumes:
      - ./observability/loki/config.yaml:/etc/loki/config.yaml:ro
      - ./data/loki:/loki
    ports:
      - "3100:3100"
    networks:
      - assistant_bridge

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped
    volumes:
      - ./observability/promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/promtail:/run/promtail
    depends_on:
      - loki
    networks:
      - assistant_bridge

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - assistant_bridge

volumes:
  postgres_data:

networks:
  assistant_bridge:
    external: true
    name: assistant_bridge

include:
  - ./nginx/compose.yaml
