auth_enabled: false
server:
  http_listen_port: 3100
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
limits_config:
  retention_period: 30d
  split_queries_by_interval: 15m
  max_cache_freshness_per_query: 10m

frontend:
  max_outstanding_per_tenant: 2048
query_scheduler:
  max_outstanding_requests_per_tenant: 8192


