"""new fields

Revision ID: 03001dcf35e0
Revises: e46147ee5c0e
Create Date: 2025-05-23 13:33:06.591457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03001dcf35e0'
down_revision: Union[str, None] = 'e46147ee5c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_to_publish_chat_secondary')
    op.add_column('publish_story_requests', sa.Column('publication_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'publish_story_requests', 'stories_to_publish', ['publication_id'], ['id'])
    op.add_column('send_post_requests', sa.Column('publication_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'send_post_requests', 'posts_to_publish', ['publication_id'], ['id'])
    op.add_column('worker_messages', sa.Column('request_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_messages', 'request_id')
    op.drop_constraint(None, 'send_post_requests', type_='foreignkey')
    op.drop_column('send_post_requests', 'publication_id')
    op.drop_constraint(None, 'publish_story_requests', type_='foreignkey')
    op.drop_column('publish_story_requests', 'publication_id')
    op.create_table('posts_to_publish_chat_secondary',
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='posts_to_publish_chat_secondary_chat_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['posts_to_publish.id'], name='posts_to_publish_chat_secondary_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_to_publish_chat_secondary_pkey')
    )
    # ### end Alembic commands ###
