"""add update_post

Revision ID: 0852bce493f4
Revises: 67c1031a7b36
Create Date: 2025-08-22 18:18:36.080556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0852bce493f4'
down_revision: Union[str, None] = '67c1031a7b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_post',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('post_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('posts_to_publish', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('send_post_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('send_post_requests', 'deleted_at')
    op.drop_column('posts_to_publish', 'deleted_at')
    op.drop_column('posts', 'deleted_at')
    op.drop_table('update_post')
    # ### end Alembic commands ###
