"""add author_id to update_post

Revision ID: 20b8c098835b
Revises: 0852bce493f4
Create Date: 2025-08-22 19:35:56.494523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b8c098835b'
down_revision: Union[str, None] = '0852bce493f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_post', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'update_post', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'update_post', type_='foreignkey')
    op.drop_column('update_post', 'author_id')
    # ### end Alembic commands ###
