"""add cascade delete to SendPostRequest

Revision ID: 33962da658bb
Revises: 4ffb6ac9b17c
Create Date: 2025-07-17 13:13:35.866874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33962da658bb'
down_revision: Union[str, None] = '4ffb6ac9b17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('send_post_requests_publication_id_fkey'), 'send_post_requests', type_='foreignkey')
    op.create_foreign_key(None, 'send_post_requests', 'posts_to_publish', ['publication_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'send_post_requests', type_='foreignkey')
    op.create_foreign_key(op.f('send_post_requests_publication_id_fkey'), 'send_post_requests', 'posts_to_publish', ['publication_id'], ['id'])
    # ### end Alembic commands ###
