"""add chat_type

Revision ID: 3ad7800f7743
Revises: 0b9fd1f0f1e4
Create Date: 2025-06-20 01:49:22.918048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ad7800f7743'
down_revision: Union[str, None] = '0b9fd1f0f1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_type',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chats', sa.Column('chat_type_id', sa.UUID(), nullable=True))
    op.add_column('chats', sa.Column('responsible_manager_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chats', 'chat_type', ['chat_type_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'users', ['responsible_manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'responsible_manager_id')
    op.drop_column('chats', 'chat_type_id')
    op.drop_table('chat_type')
    # ### end Alembic commands ###
