"""add on_delete cascade to post_to_publish_chat_association

Revision ID: 67c1031a7b36
Revises: 8d6339564a59
Create Date: 2025-08-19 10:27:57.753231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c1031a7b36'
down_revision: Union[str, None] = '8d6339564a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_to_publish_chat_association_chat_id_fkey'), 'post_to_publish_chat_association', type_='foreignkey')
    op.drop_constraint(op.f('post_to_publish_chat_association_post_to_publish_id_fkey'), 'post_to_publish_chat_association', type_='foreignkey')
    op.create_foreign_key(None, 'post_to_publish_chat_association', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_to_publish_chat_association', 'posts_to_publish', ['post_to_publish_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_to_publish_chat_association', type_='foreignkey')
    op.drop_constraint(None, 'post_to_publish_chat_association', type_='foreignkey')
    op.create_foreign_key(op.f('post_to_publish_chat_association_post_to_publish_id_fkey'), 'post_to_publish_chat_association', 'posts_to_publish', ['post_to_publish_id'], ['id'])
    op.create_foreign_key(op.f('post_to_publish_chat_association_chat_id_fkey'), 'post_to_publish_chat_association', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
