"""add format to emoji

Revision ID: 689dc9786278
Revises: b1eabbabf38f
Create Date: 2025-08-01 15:16:53.434774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '689dc9786278'
down_revision: Union[str, None] = 'b1eabbabf38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('static', 'video', 'lottie', name='format').create(op.get_bind())
    op.add_column('emojis', sa.Column('format', postgresql.ENUM('static', 'video', 'lottie', name='format', create_type=False), server_default='video', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emojis', 'format')
    sa.Enum('static', 'video', 'lottie', name='format').drop(op.get_bind())
    # ### end Alembic commands ###
