"""add_stale_statuses_and_stale_at

Revision ID: 86ebde41e948
Revises: f85214c6890e
Create Date: 2025-09-10 23:51:19.836921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86ebde41e948'
down_revision: Union[str, None] = 'f85214c6890e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old default to avoid casting 'video'::format → emoji_format
    op.execute('ALTER TABLE emojis ALTER COLUMN "format" DROP DEFAULT')
    op.alter_column(
        'emojis',
        'format',
        existing_type=postgresql.ENUM('static', 'video', 'lottie', name='format'),
        type_=sa.Enum('static', 'video', 'lottie', name='emoji_format'),
        existing_nullable=False,
        existing_server_default=sa.text("'video'::format"),
        # Cast via text and quote column to avoid ambiguity
        postgresql_using='"format"::text::emoji_format',
    )
    # Restore default on the new enum type
    op.execute("ALTER TABLE emojis ALTER COLUMN \"format\" SET DEFAULT 'video'::emoji_format")
    op.add_column('send_post_requests', sa.Column('stale_at', sa.DateTime(), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='publicationstatus',
        new_values=['PENDING', 'SCHEDULED', 'SCHEDULING', 'IN_PROGRESS', 'POSTED', 'FAILED', 'CANCELED', 'STALE'],
        affected_columns=[TableReference(table_schema='public', table_name='posts_to_publish', column_name='status'), TableReference(table_schema='public', table_name='stories_to_publish', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='sendpostrequeststatus',
        new_values=['PLANNED', 'IN_PROGRESS', 'SENT', 'FAILED', 'CANCELLED', 'STALE'],
        affected_columns=[TableReference(table_schema='public', table_name='send_post_requests', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='sendpostrequeststatus',
        new_values=['PLANNED', 'IN_PROGRESS', 'SENT', 'FAILED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='send_post_requests', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='publicationstatus',
        new_values=['PENDING', 'SCHEDULED', 'SCHEDULING', 'IN_PROGRESS', 'POSTED', 'FAILED', 'CANCELED'],
        affected_columns=[TableReference(table_schema='public', table_name='posts_to_publish', column_name='status'), TableReference(table_schema='public', table_name='stories_to_publish', column_name='status')],
        enum_values_to_rename=[],
    )

    op.drop_column('send_post_requests', 'stale_at')
    # Drop default before casting back
    op.execute('ALTER TABLE emojis ALTER COLUMN "format" DROP DEFAULT')
    op.alter_column(
        'emojis',
        'format',
        existing_type=sa.Enum('static', 'video', 'lottie', name='emoji_format'),
        type_=postgresql.ENUM('static', 'video', 'lottie', name='format'),
        existing_nullable=False,
        existing_server_default=sa.text("'video'::format"),
        # Symmetric cast back via text and quoted column
        postgresql_using='"format"::text::format',
    )
    # Restore default on the original enum type
    op.execute("ALTER TABLE emojis ALTER COLUMN \"format\" SET DEFAULT 'video'::format")
    # ### end Alembic commands ###
