"""custom emojis and message formatting

Revision ID: abcf318c89b2
Revises: 9a074f5ab93e
Create Date: 2025-05-29 20:22:05.987151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abcf318c89b2'
down_revision: Union[str, None] = '9a074f5ab93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('html', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'entities')
    op.drop_column('posts', 'html')
    # ### end Alembic commands ###
