"""unique custom_emoji_id

Revision ID: b1eabbabf38f
Revises: 33962da658bb
Create Date: 2025-07-27 16:05:09.870007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1eabbabf38f'
down_revision: Union[str, None] = '33962da658bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'emojis', ['custom_emoji_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emojis', type_='unique')
    # ### end Alembic commands ###
