"""add ondelete=SET NULL

Revision ID: be2a6b42f140
Revises: f9ca5b9dddf2
Create Date: 2025-06-01 19:36:59.737898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2a6b42f140'
down_revision: Union[str, None] = 'f9ca5b9dddf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('publish_story_requests_user_id_fkey'), 'publish_story_requests', type_='foreignkey')
    op.create_foreign_key(None, 'publish_story_requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('send_post_requests', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('send_post_requests_user_id_fkey'), 'send_post_requests', type_='foreignkey')
    op.create_foreign_key(None, 'send_post_requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('stories_to_publish_manager_id_fkey'), 'stories_to_publish', type_='foreignkey')
    op.create_foreign_key(None, 'stories_to_publish', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories_to_publish', type_='foreignkey')
    op.create_foreign_key(op.f('stories_to_publish_manager_id_fkey'), 'stories_to_publish', 'users', ['manager_id'], ['id'])
    op.drop_constraint(None, 'send_post_requests', type_='foreignkey')
    op.create_foreign_key(op.f('send_post_requests_user_id_fkey'), 'send_post_requests', 'users', ['user_id'], ['id'])
    op.alter_column('send_post_requests', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'publish_story_requests', type_='foreignkey')
    op.create_foreign_key(op.f('publish_story_requests_user_id_fkey'), 'publish_story_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
