"""entities for worker messages

Revision ID: cb956a6dcb2d
Revises: abcf318c89b2
Create Date: 2025-05-30 02:18:30.009971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb956a6dcb2d'
down_revision: Union[str, None] = 'abcf318c89b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_messages', sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_messages', 'entities')
    # ### end Alembic commands ###
