"""add last ondelete=SET NULL

Revision ID: cfdb819bfb69
Revises: be2a6b42f140
Create Date: 2025-06-01 19:42:10.343085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdb819bfb69'
down_revision: Union[str, None] = 'be2a6b42f140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('worker_messages_user_id_fkey'), 'worker_messages', type_='foreignkey')
    op.create_foreign_key(None, 'worker_messages', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_messages', type_='foreignkey')
    op.create_foreign_key(op.f('worker_messages_user_id_fkey'), 'worker_messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
