"""add cascade delete to chat on send_post_request

Revision ID: f85214c6890e
Revises: 20b8c098835b
Create Date: 2025-08-27 11:34:19.263099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85214c6890e'
down_revision: Union[str, None] = '20b8c098835b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('send_post_requests_chat_id_fkey'), 'send_post_requests', type_='foreignkey')
    op.create_foreign_key(None, 'send_post_requests', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'send_post_requests', type_='foreignkey')
    op.create_foreign_key(op.f('send_post_requests_chat_id_fkey'), 'send_post_requests', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
