"""add ondelete=SET NULL to PostToPublish

Revision ID: f9ca5b9dddf2
Revises: 483f44f59cc3
Create Date: 2025-06-01 19:31:16.800387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ca5b9dddf2'
down_revision: Union[str, None] = '483f44f59cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_to_publish', 'manager_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('posts_to_publish_manager_id_fkey'), 'posts_to_publish', type_='foreignkey')
    op.create_foreign_key(None, 'posts_to_publish', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts_to_publish', type_='foreignkey')
    op.create_foreign_key(op.f('posts_to_publish_manager_id_fkey'), 'posts_to_publish', 'users', ['manager_id'], ['id'])
    op.alter_column('posts_to_publish', 'manager_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
