services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/github-runner/acme-challenge:/home/github-runner/acme-challenge
    restart: always
    networks:
      - default
      - assistant_bridge
