{
 "title": "logs by service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "worker_container", "label": "worker", "query": "label_values(container)" }
  ]
 },
 "panels": [
  {
   "title": "workers (by container)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container=~\"$worker_container\"}"
    }
   ]
  },
  {
   "title": "backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"admin-backend\"} |= ``"
    }
   ]
  },
  {
   "title": "bot",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"bot\"} |= ``"
    }
   ]
  },
  {
   "title": "posts",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"posts\"} |= ``"
    }
   ]
  },
  {
   "title": "worker manager",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"worker-manager\"} |= ``"
    }
   ]
  },
  {
   "title": "db",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"db\"} |= ``"
    }
   ]
  },
  {
   "title": "watcher",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"watcher\"} |= ``"
    }
   ]
  }
 ]
}