name: DEPLOY


on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy all
    runs-on: [
      "self-hosted",
      "prod"
    ]
    env:
      DEPLOY_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          touch .env
          touch ./posts-service/jobs.sqlite

          make bw
          make mn

          if [ "$DEPLOY_ENV" = "prod" ]; then
            cp prod.env .env

            DOMAIN="https://ai.avocado.ceo"

            echo "" >> .env
            echo "APP_HOST=${DOMAIN}" >> .env
            echo "MINIAPP_URL=${DOMAIN}" >> .env
            echo "HOST_UPLOAD_DIR=~/upload" >> .env

            echo "VITE_API_BASE=${DOMAIN}/api" > admin/frontend/.env
          fi

      - name: Compose up
        run: |
          sudo docker compose up --build -d

      - name: Cleanup
        run: |
          sudo docker system prune -a -f --filter "label!=keep"
