name: DEPLOY


on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy all
    runs-on: [
      "self-hosted",
      "prod"
    ]
    defaults:
      run:
        working-directory: repo
    env:
      DEPLOY_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false   # avoid deleting workspace with root-owned data/
          fetch-depth: 0
          path: repo     # checkout into subdir to avoid cleaning workspace root

      - name: Prepare environment
        run: |
          touch .env
          touch ./posts-service/jobs.sqlite

          # persistent dirs for logs/state (survive docker system prune -af)
          sudo mkdir -p ./data/loki ./data/grafana ./data/promtail
          sudo chmod -R 0777 ./data

          make bw
          make mn

          if [ "$DEPLOY_ENV" = "prod" ]; then
            cp prod.env .env

            DOMAIN="https://ai.avocado.ceo"

            echo "" >> .env
            echo "APP_HOST=${DOMAIN}" >> .env
            echo "MINIAPP_URL=${DOMAIN}" >> .env
            echo "HOST_UPLOAD_DIR=/root/upload" >> .env

            echo "VITE_API_BASE=${DOMAIN}/api" > admin/frontend/.env
          fi

      - name: Compose up
        run: |
          sudo docker compose up --build -d --force-recreate

      - name: Cleanup
        run: |
          sudo docker system prune -a -f --filter "label!=keep"
